name: CI - clone App and Execute Test

on: 
    push:
        branches: [main]
    pull_request:
        branches: [main]
        
jobs:
    tests:
        runs-on: ubuntu-latest

        services: 
            mongo: 
                image: mongo:6.0
                ports:
                    - 27017:27017

        env:
            MONGO_URI: ${{ secrets.MONGO_URI }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}      
            PORT: 6007
            VITE_API_URL: http://localhost:6007/api
    
        steps:
            - name: Checkout current repo
              uses: actions/checkout@v3

            - name: Clone Repo Athena Redux Bank
              run: |
                  git clone https://github.com/juantor16/redux-athena-bank.git app

            - name: Create .env File for Backend
              run: |
                  echo "MONGO_URI=${{ env.MOGO_URI }}" > app/backend/.env  
                  echo "JWT_SECRET=${{ env.JWT_SECRET }}" >> app/backend/.env  
                  echo "PORT=${{ env.PORT }}" >> app/backend/.env  
                  echo "VITE_API_URL=${{ env.VITE_API_URL }}" >> app/backend/.env  

            - name: Installing Backend Dependencies
              run: |
                  cd app/backend
                  npm install 
          
            - name: Set Backend
              run: |
                  cd app/backend
                  npm run dev > backend.log 2>&1 &

            #Install Globally wait-on
            - name: Installing wait-on
              run: npm install -g wait-on

            #Wait Backend is set in port 6007
            - name: Waiting Backend is set
              run: wait-on tcp:localhost:6007
          
            #Install Front End Dependencies
            - name: Install Front End dependencies   
              run: |
                  cd app/frontend
                  npm install
              env: 
                VITE_API_URL: ${{ env.VITE_API_URL }}

            #Wait Front is set
            - name: Waiting Frontend is set
              run: wait-on http://localhost:3000
                           
                      